AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  API:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      CodeUri: API/.
      Description: Store data in Mongodb
      Timeout: 5
      MemorySize: 128
      # Function's execution role
      Tracing: Active
      Events:
        API:
          Type: Api
          Properties:
            Path: /hello
            Method: post
      Environment:
        Variables:
          MONGODB_URL: ${MONGODB_URL}